### ISSUE TITLE
Review and prepare beds and bedrooms variable

### ISSUE THREAD

**Issue by MerelvStekelenburg** [course-dprep/team-assignment-team-10#16]

**Comment by MerelvStekelenburg** [comment]
There are some NA's for the bedrooms variable. I checked a few and they either have 1 bedroom or the listing is a studio/has 1 room in total. How should I proceed from here? Should I classify the NAs as 1 bedroom?

**Comment by MerelvStekelenburg** [comment]
There are also some NA's in the beds variable. Is it best to leave those and exclude them from the analysis? I manually checked a few listings and they all have a different number of beds so replacing an NA with a 1 would not be accurate.

**Comment by Ana042** [comment]
I don't think it's safe to make any assumptions since there is no pattern in the two columns, so the only option I see is excluding them

**Comment by Ana042** [comment]
we could also replace the NAs with the mean value

**Comment by MerelvStekelenburg** [comment]
Created a pull request for the code to prepare the data. NAs in bedrooms replace with 1 if the listing type is hotel room, private room, or shared room. NAs in beds replaced with 1 if the listing accommodates 1.
