### ISSUE TITLE
Missing text in bathrooms_text column

### ISSUE THREAD

**Issue by Ana042** [course-dprep/team-assignment-team-10#18]
I just discovered that there are 23 listings that do not have any text offering information about bathrooms. What should we do about this? We could replace them with NAs and have them ignored when we perform the analysis

**Comment by MerelvStekelenburg** [comment]
I think it is best to replace them with NAs and exclude them from analysis since it's only 23 listings. 

> I just discovered that there are 23 listings that do not have any text offering information about bathrooms. What should we do about this? We could replace them with NAs and have them ignored when we perform the analysis
