### ISSUE TITLE
proposed rq's

### ISSUE THREAD

**Issue by Ana042** [course-dprep/team-assignment-team-10#3]
1. How was the housing market in X* city affected by Covid-19?
2. What changes did Covid-19 bring into the consumer behavior in terms of housing preferences?
   2.1. Did the demand for long-term stays (30+ days) increase as a result of the Covid-19 pandemic?
3. Do the listings of "superhosts" get booked more?

**Comment by KorayKul** [comment]
How does neighborhood effects the price of the listings in Amsterdam? (and maybe we can use number of rooms as a control variable.)

**Comment by MerelvStekelenburg** [comment]
Do superhosts [https://www.airbnb.com/help/article/829/how-to-become-a-superhost] on average charge more for their listing and are these listings more popular (get booked more frequently) than listings of non-superhosts?

**Comment by MerelvStekelenburg** [comment]
> How does neighborhood effects the price of the listings in Amsterdam? (and maybe we can use number of rooms as a control variable.)

@KorayKul Do you mean the number of listings available in a particular neighborhood with the number of rooms? Or the number of rooms within a listing?

**Comment by Ana042** [comment]
How did the consumer behavior change over the last year? Was there a change in the average nights booked and type of accommodation and if so, how were they influenced by the price changes?

**Comment by KorayKul** [comment]
> > How does neighborhood effects the price of the listings in Amsterdam? (and maybe we can use number of rooms as a control variable.)
> 
> @KorayKul Do you mean the number of listings available in a particular neighborhood with the number of rooms? Or the number of rooms within a listing?

@MerelvStekelenburg The number of rooms within a listing. If we don't use this control variable our findings may be biased. Because questions like "How many number of rooms is in this listing?" or "How many people can stay there?" may also have direct effect on the price for a particular listing.

**Comment by MerelvStekelenburg** [comment]
> 

Instead of a variable like number of rooms something like "number of beds" may be clearer

**Comment by MerelvStekelenburg** [comment]
> > > How does neighborhood effects the price of the listings in Amsterdam? (and maybe we can use number of rooms as a control variable.)
> > 
> > 
> > @KorayKul Do you mean the number of listings available in a particular neighborhood with the number of rooms? Or the number of rooms within a listing?
> 
> @MerelvStekelenburg The number of rooms within a listing. If we don't use this control variable our findings may be biased. Because questions like "How many number of rooms is in this listing?" or "How many people can stay there?" may also have direct effect on the price for a particular listing.

Maybe in this case it might be more clear to use the number of beds instead of the number of rooms.

**Comment by MerelvStekelenburg** [comment]
> How did the consumer behavior change over the last year? Was there a change in the average nights booked and type of accommodation and if so, how were they influenced by the price changes?

Maybe we could compare the summer of 2019 with the summer of 2020/2021 to link it to covid?

**Comment by alebock** [comment]
New proposed RQ: 

**How do the property amenities influence the listing price per neighbourhood in Hawaii?**

...listing price vs. listing price range...

**Comment by MerelvStekelenburg** [comment]
> New proposed RQ:
> 
> **How do the property amenities influence the listing price per neighbourhood in Hawaii?**
> 
> ...listing price vs. listing price range...

Maybe we can select the top 10 or 20 neighborhoods with the most listings? Or make a requirement for a minimum number of listings per neighborhood to include a neighborhood in the analysis.

**Comment by Ana042** [comment]
> New proposed RQ:
> 
> **How do the property amenities influence the listing price per neighbourhood in Hawaii?**
> 
> ...listing price vs. listing price range...

To combine the calendar with the listings table we could instead check seasonality instead of neighbourhoods. So it would rather be **How do the property amenities influence the listing price per season in Hawaii?**

**Comment by MerelvStekelenburg** [comment]
What also might be interesting is comparing the summer months (June - August) to the surfing season in Hawaii (November - February) instead of the neighborhoods. Then we also use the calendar csv file. 

New proposed RQ:
**How do the amenities of a listing influence the price of a listing in Hawaii and how does this differ between the surf season (November - February) and the summer season (June - August) ?**

**Comment by alebock** [comment]
> What also might be interesting is comparing the summer months (June - August) to the surfing season in Hawaii (November - February) instead of the neighborhoods. Then we also use the calendar csv file.
> 
> New proposed RQ: **How do the amenities of a listing influence the price of a listing in Hawaii and how does this differ between the surf season (November - February) and the summer season (June - August) ?**

> I don't think the results will bee too meaningful. Likely, both surf season and summer season would be highly booked because of the holiday destination. So, probably no significant difference...

**Comment by Ana042** [comment]
> What also might be interesting is comparing the summer months (June - August) to the surfing season in Hawaii (November - February) instead of the neighborhoods. Then we also use the calendar csv file.
> 
> New proposed RQ: **How do the amenities of a listing influence the price of a listing in Hawaii and how does this differ between the surf season (November - February) and the summer season (June - August) ?**

Updated RQ:
**How to the property characteristics influence the price of a listing in Hawaii and how does it differ between seasons (spring/summer/autumn/winter)?**

-list of characteristics (IVs) will be made
