### ISSUE TITLE
make list of important variables

### ISSUE THREAD

**Issue by alebock** [course-dprep/team-assignment-team-10#5]
IV s to include in regression from listings dataset (Hawaii)
- (optional) **neighbourhood_group_cleansed** (variable takes values: Hawaii, Honolulu, Kauai, Maui)
- **room_type** (variable takes values: Entire home/apt, Private room, Shared room, Hotel room)
- **accommodates** (numeric, number pdf people that can stay at the property)
- **bathrooms_text** (need to extract the number of baths and type of bath (?/shared/private)
- **bedrooms** (numeric)
- **beds** (numeric)
- **instant_bookable** (boolean)

Optional IVs (might be interesting)
- **review_scores_rating**
- review_scores_accuracy
- review_scores_cleanliness
- review_scores_checkin
- review_scores_communication
- review_scores_location
- review_scores_value

DV
- **price** (calendar datafile)

Group by:
- **season** (calendar datafile)

Merge by:
- id

**Comment by Ana042** [comment]
I will take the **bathrooms_text**

**Comment by alebock** [comment]
I'll take **room_type** and **neighbourhood_group_cleansed**

**Comment by MerelvStekelenburg** [comment]
I'll review **bedrooms** & **beds**

**Comment by KorayKul** [comment]
I will review accomodates and and instant_bookable

**Comment by alebock** [comment]
I will also take the overall review scores, we also decided not to include the detailed review scores.
